CXX = g++
CCFLAGS = -g --std=c++14 -Wall -Werror -pedantic

# this is a "Suffix Rule" - how to create a .o from a .cc file

test_tree: test_tree.cc
	$(CXX) $(CCFLAGS) -o test_tree test_tree.cc

all:  tree
